bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9
}

rent_choices ={
    '500': '$500',
    '600': '$600',
    '700': '$700',
    '800': '$800',
    '900': '$900',
    '1000': '$1,000',
    '1100': '$1,100',
    '1200': '$1,200',
    '1300': '$1,300',
    '1400': '$1,400',
    '1500': '$1,500',
    '1600': '$1,600',
    '1700': '$1,700'
    
}

city_choices = {
    'Axis' : 'Axis',
    'Bayou La Batre' : 'Bayou La Batre',
    'Bucks' : 'Bucks',
    'Chickasaw' : 'Chickasaw',
    'Chunchula' : 'Chunchula',
    'Citronelle' : 'Citronelle',
    'Coden' : 'Coden',
    'Creola' : 'Creola',
    'Dauphin Island' : 'Dauphin Island',
    'Eight Mile' : 'Eight Mile',
    'Grand Bay' : 'Grand Bay',
    'Irvington' : 'Irvington',
    'Mobile' : 'Mobile',
    'Mount Vernon' : 'Mount Vernon',
    'Movica' : 'Movica',
    'Prichard' : 'Prichard',
    'St. Elmo' : 'St. Elmo',
    'Saraland' : 'Saraland',
    'Satsuma' : 'Satsuma',
    'Semmes' : 'Semmes',
    'Theodore' : 'Theodore',
    'Tillmans Corner' : 'Tillmans Corner',
    'Wilmer' : 'Wilmer',
    
}
state_choices = {
    'AL':'Alabama',
    'AK':"Alaska",
    'AZ':'Arizona',
    'AR':'Arkansas',
    'CA':'California',
    'CO':'Colorado',
    'CT':'Connecticut',
    'DE':'Delaware',
    'DC':'District Of Columbia',
    'FL':'Florida',
    'GA':'Georgia',
    'HI':'Hawaii',
    'ID':'Idaho',
    'IL':'Illinois',
    'IN':'Indiana',
    'IA':'Iowa',
    'KS':'Kansas',
    'KY':'Kentucky',
    'LA':'Louisiana',
    'ME':'Maine',
    'MD':'Maryland',
    'MA':'Massachusetts',
    'MI':'Michigan',
    'MN':'Minnesota',
    'MS':'Mississippi',
    'MO':'Missouri',
    'MT':'Montana',
    'NE':'Nebraska',
    'NV':'Nevada',
    'NH':'New Hampshire',
    'NJ':'New Jersey',
    'NM':'New Mexico',
    'NY':'New York',
    'NC':'North Carolina',
    'ND':'North Dakota',
    'OH':'Ohio',
    'OK':'Oklahoma',
    'OR':'Oregon',
    'PA':'Pennsylvania',
    'RI':'Rhode Island',
    'SC':'South Carolina',
    'SD':'South Dakota',
    'TN':'Tennessee',
    'TX':'Texas',
    'UT':'Utah',
    'VT':'Vermont',
    'VA':'Virginia',
    'WA':'Washington',
    'WV':'West Virginia',
    'WI':'Wisconsin',
    'WY':'Wyoming' 
}